# Generated by Django 4.2.3 on 2023-07-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scamming', '0002_collecting_location_collecting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecting',
            name='marital_status',
            field=models.CharField(default='single', max_length=10),
        ),
    ]
