# Generated by Django 4.2.3 on 2023-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='your user name', max_length=100)),
                ('email_address', models.EmailField(default='your email', max_length=100)),
                ('password', models.CharField(default='use strong password', max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
    ]
