# Generated by Django 4.2.3 on 2023-07-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='accounts.signup'),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logging', to='accounts.signup'),
        ),
    ]
