# Generated by Django 4.2.3 on 2023-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='your password', max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(default='your username', max_length=100),
        ),
    ]
