# Generated by Django 4.2.3 on 2023-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_post_updated_at_alter_topic_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message',
            field=models.TextField(default="what's on your mind", max_length=4000),
        ),
    ]
