# Generated by Django 4.2.3 on 2023-07-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_topic_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='starter',
        ),
    ]
